.TH PGAGetRTRWindowSize 3 "2020-03-31" " " "PGAPack"
.SH NAME
PGAGetRTRWindowSize \- returns the size of the retricted tournament
window.
.SH INPUT PARAMETERS
.PD 0
.TP
ctx
- context variable
.PD 1
.SH OUTPUT PARAMETERS
.PD 0
.TP
none

.PD 1
.SH SYNOPSIS
.nf
#include "pgapack.h"
int PGAGetRTRWindowSize(PGAContext *ctx)
.fi
.SH LOCATION
select.c
.SH EXAMPLE
.nf
Example:
PGAContext *ctx;
int size;
:
size = PGAGetRTRWindowSize(ctx);

.fi
