.TH PGASetTournamentSize 3 "2020-05-31" " " "PGAPack"
.SH NAME
PGASetTournamentWithReplacement \- Specifies if tournament is with or
without replacement.
.SH DESCRIPTION
This function will have no effect unless
PGA_SELECT_TOURNAMENT was specified as the type of selection to use
with PGASetSelectType. The default value is PGA_TRUE.
.SH INPUT PARAMETERS
.PD 0
.TP
ctx
- context variable
.PD 0
.TP
v
- the value, PGA_TRUE or PGA_FALSE
.PD 1
.SH OUTPUT PARAMETERS
.PD 0
.TP
none

.PD 1
.SH SYNOPSIS
.nf
#include "pgapack.h"
void  PGASetTournamentWithReplacement(PGAContext *ctx, int value)
.fi
.SH LOCATION
select.c
.SH EXAMPLE
.nf
Example:
PGAContext *ctx;
:
PGASetTournamentSize(ctx, PGA_FALSE);

.fi
