#!/usr/bin/python3

import sys
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from argparse import ArgumentParser

def plot_file (f, args, n) :
    X = []
    Y = []
    Z = []
    title = args.title
    for line in f :
        line = line.strip ()
        if line.startswith ('Example:') or line.startswith ('Title:') :
            title = line.split (None, 1) [-1]
        if line.startswith ('F') and line [1].isspace () :
            f, idx, number = line.split ()
            idx = int (idx)
            num = float (number)
            if idx == args.y_axis :
                Y.append (num)
            elif idx == args.x_axis :
                X.append (num)
            elif idx == args.z_axis :
                Z.append (num)
    if args.title :
        title = args.title
    x_label = args.x_label or 'Objective %d' % args.x_axis
    y_label = args.y_label or 'Objective %d' % args.y_axis
    z_label = args.z_label or 'Objective %d' % args.z_axis

    d = dict (facecolors = 'none', linewidths = 0.5, s = 12)
    fig = plt.figure ()
    ax  = fig.add_subplot (111, projection = '3d')
    ax.scatter (X, Y, Z, edgecolors='C%d' % (n % 10), **d)
    ax.set_xlabel (x_label)
    ax.set_ylabel (y_label)
    ax.set_zlabel (z_label)
    return title

cmd = ArgumentParser ()
cmd.add_argument \
    ( "filename"
    , help    = "Filename to read optimization data from, default stdin"
    , nargs   = '*'
    )
cmd.add_argument \
    ( "-n", "--title"
    , help    = "Default title of the plot, will be overwritten by "
                "'Example' or 'Title' line"
    , default = ''
    )
cmd.add_argument \
    ( "-x", "--x-axis"
    , type    = int
    , default = 0
    )
cmd.add_argument \
    ( "-X", "--x-label"
    , help    = "Label for X-Axis"
    )
cmd.add_argument \
    ( "-y", "--y-axis"
    , type    = int
    , default = 1
    )
cmd.add_argument \
    ( "-Y", "--y-label"
    , help    = "Label for Y-Axis"
    )
cmd.add_argument \
    ( "-z", "--z-axis"
    , type    = int
    , default = 2
    )
cmd.add_argument \
    ( "-Z", "--z-label"
    , help    = "Label for Z-Axis"
    )
args = cmd.parse_args ()
f  = sys.stdin
if args.filename :
    for n, fn in enumerate (args.filename) :
        with open (fn, 'r') as f :
            title = plot_file (f, args, n)
else :
    title = plot_file (f, args, 0)

plt.title (title)
plt.show ()
